### ISSUE TITLE
error_log message on default install

### ISSUE THREAD

**Issue by drllz** [robiso/wondercms#189] opened 2020-02-20 21:52 UTC
Apologies, but I am unable to register to the forum on wondercms.com. It does not proceed past the "I agree to these terms" in the Registration process.

Just downloaded WonderCMS 3.0.6 to my webspace and tried to navigate to index.php
Just an empty page appeared.
however an error_log appeared  in root directory which reads : 
> [20-Feb-2020 14:27:30 America/Boise] PHP Parse error:  syntax error, unexpected 'const' (T_CONST), expecting variable (T_VARIABLE) in /home1/cart1/public_html/jn/wonder/index.php on line 21

I'm hosted on Bluehost, with PHP 7.2.7 + curl + mbstring extensions enabled

What can I do to fix?

**Comment by robiso** [comment] 2020-02-22 14:23
@drllz hi and welcome. No worries at all!

Are you sure you're running on PHP 7.2+? Is there somehow you can verify that version is active on your webserver?

Please check this thread: https://github.com/robiso/wondercms/issues/175 (where this issue was caused by an older PHP version).
Same thread with posted solution: https://github.com/robiso/wondercms/issues/175#issuecomment-569533969
This happens on versions 7.1 and prior, due to the visibility of class constants that was only added in PHP 7.1.

**Comment by robiso** [comment] 2020-03-10 13:22
Closing issue, please feel free to-reopen if it's relevant to your.

**Closed** 2020-03-10 13:22 UTC
Labels: duplicate
