### ISSUE TITLE
trouble installing WonderCMS via Docker

### ISSUE THREAD

**Issue by mptpro** [robiso/wondercms#288] opened 2023-03-08 07:43 UTC
I hope this is the correct place to ask this. 

I am trying to install WonderCMS via Docker as per instructions here: https://github.com/robiso/docker-wondercms

I am running docker on Linux PopOS.

When I run the command `docker build -t robiso/wondercms .`

i get the error: 

```
[+] Building 0.0s (2/2) FINISHED                                   
 => [internal] load .dockerignore                             0.0s
 => => transferring context: 2B                               0.0s
 => [internal] load build definition from Dockerfile          0.0s
 => => transferring dockerfile: 2B                            0.0s
ERROR: failed to solve: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount3997035681/Dockerfile: no such file or directory

```

**Comment by robiso** [comment] 2023-03-19 18:08
Hello @mptpro, never seen anyone run into this issue before.

When checking stackoverflow for similar issues:

Possible solutions:
1. Before running docker build, can you try to "cd" into the correct folder?

Other solutions posted here (to avoid copying everything): https://stackoverflow.com/questions/32997269/copying-a-file-in-a-dockerfile-no-such-file-or-directory

**Comment by robiso** [comment] 2023-03-20 18:21
I've tried updating the Docker repository to latest versions, can you re-download and retry?

From stackoverflow, I would assume the correct folder is where the WonderCMS image is present.
The closest I could find was: https://github.com/mablanco/docker-wondercms

**Comment by robiso** [comment] 2023-03-24 15:48
@mptpro 

No worries, hopefully we'll get this sorted out.
I updated the report again, this time the readme.

When you try with docker build -t WonderCMS/wondercms? Since we changed the repository from robiso/wondercms to WonderCMS/wondercms

**Comment by seergidev** [comment] 2023-03-28 01:18
I can't make it work either, but be aware I'm using podman right now.

The first problem is the image: `php:7.4-apache-stretch` does not seem to exist! I checked in Dockerhub.
I replace the image with `php:7.4-apache` and it works. But then I get this error when building:

> STEP 5/8: RUN docker-php-ext-configure zip --with-libzip &&     docker-php-ext-install -j$(nproc) zip
Configuring for:
PHP Api Version:         20190902
Zend Module Api No:      20190902
Zend Extension Api No:   320190902
configure: error: unrecognized options: --with-libzip
Error: building at STEP "RUN docker-php-ext-configure zip --with-libzip &&     docker-php-ext-install -j$(nproc) zip": while running runtime: exit status 1

The problem now is the `--with-libzip` option, so I removed it. And then it seems to work (at least the build process) but in the browser I get this error:

> Fatal error: Uncaught Exception: Could write to data folder. in /var/www/html/index.php:409 Stack trace: #0 /var/www/html/index.php(874): Wcms->checkFolder('/var/www/html/t...') #1 /var/www/html/index.php(106): Wcms->getDb() #2 /var/www/html/index.php(14): Wcms->__construct() #3 {main} thrown in /var/www/html/index.php on line 409

Perhaps this second error is because I'm using podman/Fedora in my laptop. Tomorrow I'll check with Docker on Ubuntu.

**Comment by seergidev** [comment] 2023-03-28 08:17
I checked with Docker under Ubuntu and I have the same issue. I'll try to figure it out.

**Comment by seergidev** [comment] 2023-03-28 09:32
I found a Dockerfile that actually works:
https://github.com/mablanco/docker-wondercms

```
FROM php:7.4.9-apache-buster
ENV DEBIAN_FRONTEND noninteractive
ARG WONDERCMS_VERSION=3.1.4
WORKDIR /var/www/html
RUN apt-get update && \
    apt-get -yqu dist-upgrade && \
    apt-get -yq install git zip libzip-dev && \
    apt-get -yq autoremove && \
    apt-get clean && \
    rm -rf /var/lib/{apt,dpkg,cache,log}
RUN git clone --depth 1 https://github.com/robiso/wondercms.git -b $WONDERCMS_VERSION . && \
    mv $PHP_INI_DIR/php.ini-development $PHP_INI_DIR/php.ini && \
    docker-php-ext-configure zip && \
    docker-php-ext-install -j$(nproc) zip && \
    a2enmod rewrite && \
    chown -R www-data.www-data .
EXPOSE 80
```

I replaced version 3.1.4 for 3.4.1 and still works. I belive is a permission issue (see the final chown command).

**Comment by robiso** [comment] 2023-03-29 20:02
Thank you @seergidev I'll add this to our documentation/repository as well.

Does this work with out dockerfile as well if the permissions are set as explained above?

**Comment by seergidev** [comment] 2023-03-30 22:18
Yes, I can confirm it works with your (modified) Dockerfile using podman, so it's fair to say it's going to work with Docker.

The modified Dockerfile is as follows:
```
# WonderCMS in Docker
# See README for instructions on running this image
FROM php:7.4-apache

ENV WCMS_VERSION 3.4.1

LABEL org.label-schema.name="wondercms" \
    org.label-schema.description="Run wondercms in docker" \
    org.label-schema.url="https://www.wondercms.com/" \
    org.label-schema.vcs-url="https://github.com/WonderCMS/wondercms" \
    org.label-schema.version=$WCMS_VERSION \
    org.label-schema.maintainer="@wondercms on twitter" \
    org.label-schema.schema-version="1.0"

RUN DEBIAN_FRONTEND=noninteractive apt-get update \
    && apt-get install -y libzip-dev zip \
    && a2enmod rewrite \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && mv $PHP_INI_DIR/php.ini-development $PHP_INI_DIR/php.ini

RUN docker-php-ext-configure zip && \
    docker-php-ext-install -j$(nproc) zip

COPY . /var/www/html/

RUN chown -R www-data:www-data /var/www/html

EXPOSE 80
```
Note the change in the RUN chown command: There must be ':' between the user and the group, not '.' as indicated in the mablanco version.

**Comment by seergidev** [comment] 2023-03-31 09:57
You have not done anything wrong. It seems that Docker is not able to connect to Debian repositories, or even it has no internet connection at all.

I would try to check your internet connection and access to debian repositories from your host machine first with  
`ping -c 5 deb.debian.org`.

Then you could restart the Docker daemon: `systemctl restart docker` and try to build the image again.

You can also check if your Docker containers have access to internet:
` docker run --rm -ti alpine `
And send  
`ping -c 5 deb.debian.org` from the terminal.

If the previous ping command inside the alpine container fails, try to ping directly to their IP adress:
`ping -c5 151.101.134.132` (is the IP of deb.debian.org)

If the first ping does not work but the second one does, it means your Docker has problems resolving DNS names. If both fails, your Docker containers do not have access to internet.

Type `exit` to quit the container.

I found this thread in stackoverflow that might help:
https://stackoverflow.com/questions/51034120/docker-could-not-resolve-deb-debian-org

**Comment by robiso** [comment] 2023-05-02 13:22
@mptpro this still could be a permission issue with your Apache configuration:
https://www.makeuseof.com/you-dont-have-permission-to-access-on-this-server/

**Comment by robiso** [comment] 2023-05-10 12:57
Since the docker docs are now updated and working as confirmed by @seergidev.
Updated docker: https://github.com/robiso/docker-wondercms

@mptpro please feel free to continue commenting for additional support.

Thank you @seergidev and @mptpro 🍺

**Closed as completed by robiso** 2023-05-10 12:57 UTC
