### ISSUE TITLE
[Bug/Request] Proper UTF-8 in admin/settings fields

### ISSUE THREAD

**Issue by tamascz** [robiso/wondercms#195] opened 2020-04-06 07:36 UTC
E.g. `Röyksopp` instead of `RÃ¶yksopp`, `Sundfør` instead of `SundfÃ¸r`.
Pages that names contains these characters not be deleted in admin.

**Comment by robiso** [comment] 2020-04-07 16:07
@tamascz I see this is only an issue in when trying to add menu items. Will look into it and thanks for the report.

**Comment by TechArea** [comment] 2020-04-23 21:38
Could you add also Emoji support for menu titles?

**Comment by robiso** [comment] 2020-04-24 10:44
@TechArea, emojis are already supported and can be pasted for menu titles.
😀 -> try pasting this in the menu.

**Comment by TechArea** [comment] 2020-04-24 11:24
Hm... doesn't work here :-/

<img width="1159" alt="Screenshot 2020-04-24 at 13 08 46" src="https://user-images.githubusercontent.com/16351455/80207674-e06bcc00-862e-11ea-9c8e-3489bd60afb8.png">

<img width="1147" alt="Screenshot 2020-04-24 at 13 08 53" src="https://user-images.githubusercontent.com/16351455/80207681-e5c91680-862e-11ea-816c-696d018c685f.png">

**Comment by robiso** [comment] 2020-04-24 15:54
@TechArea what browser and operating system are you using?

**Comment by TechArea** [comment] 2020-04-24 15:58
macOS 10.15.4 (19E287), Safari Version 13.1 (15609.1.20.111.8)

**Comment by robiso** [comment] 2020-04-24 20:35
@TechArea, I'm testing on the exact same setup and it's working ok.
Can you try this emoji: 😀 
- it might be some are unsupported
- also, are you trying this out on the official demo?

**Comment by TechArea** [comment] 2020-04-24 21:55
Hm... the demo seams to work. At least, it doesn't generate wild characters. But it doesn't change (maybe that's forbidden?). I've tested your pasted Emoji and it doesn't work.

**Comment by robiso** [comment] 2020-05-01 05:51
@TechArea can you explain a bit more of what doesn't change?
On what type of server are you trying this out, some specs would be helpful to try and debug why this is happening on some servers.

**Comment by TechArea** [comment] 2020-05-11 13:14
On the demo page, the title is not applied when saving. But this is probably intended.
It's a shared hosting (LiteSpeed Server mit HTTP/2, php7).

**Comment by robiso** [comment] 2020-05-11 13:58
@TechArea you said

> On the demo page, the title is not applied when saving. But this is probably intended.
But whenever I do changes on the demo it successfully saved?

I managed to reproduce the issue somewhere else, but please get back to me in regards to what doesn't get saved on the demo (if everything works correctly on the demo I would also highly appreciate it if you can confirm that).

**Comment by robiso** [comment] 2020-05-11 18:18
Update: I'm still not positive on why this can be reproduced only on all WonderCMS installations at the / (root) of the server, all instances hosted in a subfolder/subdomain don't seem to display the emojis proparely.

**Comment by robiso** [comment] 2020-05-15 22:01
@TechArea @tamascz 
@slavenstancic and I finally managed to figured out why the special characters were broken, whenever the statistics plugin is enabled, it renders/encodes the characters incorrectly.

There's a pull request already pending to be merged https://github.com/StephanStanisic/simple-statistics/ and a new version should be released shortly.

**Comment by robiso** [comment] 2020-05-17 18:02
Closing issue as we've pushed out updates both for WonderCMS and Statistics plugin, which resolve all of the mentioned issues above.

**Closed by robiso** 2020-05-17 18:02 UTC
Labels: bug, code-review, feature finished on dev branch, fixed
