### ISSUE TITLE
Pulling Version Number Not Working

### ISSUE THREAD

**Issue by Alamantus** [robiso/wondercms#35] opened 2017-05-30 14:08 UTC
I had an old version of WonderCMS installed while testing the version 2.1.0, and was not prompted for an upgrade. I believe we need to use the Github API to accurately get the raw files rather than using `raw.githubusercontent.com`.

Here is a Stackoverflow article that makes me think this is so: https://stackoverflow.com/a/22314262

I don't know why it worked in the past and doesn't seem to be working now, but things change with APIs and file access pretty frequently with larger content hosting sites like Github, so maybe something changed recently?

I'll work on figuring the API out and get a pull request up to fix this as soon as I can.

**Comment by wdj-ac** [comment] 2017-05-30 14:30
I am not able to reproduce the issue, but you are right, API is always the better solution.
Here you can test in my environment: http://wondercms.jordin.eu/ (resets every 15 min. with old version 2.06)

**Comment by robiso** [comment] 2017-05-30 15:13
@Alamantus thanks for reporting this. This happens to me sometimes due to GitHub actually delaying the update process - not sure what causes this.

Did you try logging out and in again, as the "Update" button shows only once each time you log in.

**Comment by Alamantus** [comment] 2017-05-30 15:23
Oh, you are correct! I was somehow still logged in when I swapped subdirectories to test. The update prompt does show up when you first log in. Sorry about that!

But I do still think it is best to use the Github API, so I will work on implementing that at a more relaxed pace. :smile:

**Comment by robiso** [comment] 2017-05-30 16:01
You're awesome and thanks for confirming. Like you said, we're in no hurry and its questionable if we'll need this. :+1:  A backup plan always comes in handy!

Closing issue for now.

**Closed by robiso** 2017-05-30 16:01 UTC
